### ISSUE TITLE
Error when getting secrets from a keyvault when one secret is disabled

### ISSUE THREAD

**Issue by philippengani** [zypp-io/keyvault#25]
While using the package, I noticed that the code crashes when getting secrets from a keyvault that has one secret disabled.

How to reproduce:

- Disable a 

While using the package to fetch secrets from an Azure Key Vault, I encountered an issue where the code crashes if the Key Vault contains a secret that is disabled. This behavior disrupts the secret retrieval process, as the package does not seem to handle disabled secrets gracefully.

Steps to Reproduce:

	1.	Set up an Azure Key Vault with multiple secrets, ensuring that at least one of the secrets is in a disabled state.
	2.	Use the package to retrieve secrets from the Key Vault.
	3.	Observe that the process crashes when encountering the disabled secret.

Expected Behavior:
The package should skip or handle disabled secrets without crashing, potentially by logging a warning or returning a meaningful response, allowing the process to continue fetching valid secrets.

Actual Behavior:
The code crashes when it attempts to access a disabled secret, causing an interruption in the retrieval process.

Environment:
	•	Package version: 0.2.0

![CleanShot 2024-09-18 at 21 55 25@2x](https://github.com/user-attachments/assets/9ace04e6-e91f-449f-b2a8-343c79a8665f)

**Comment by melvinfolkers** [comment]
@philippengani after you installed the updated package 0.2.1. It should work again 👍🏻

**Comment by philippengani** [comment]
@melvinfolkers, the issue is solved after the update.
